name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: papeloto/action-zip@v1
        with:
          files: script
          recursive: true
          dest: zip
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: shallwefootball/s3-upload-action@master
      name: Release to S3
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_ACCESS_SECRET}}
        aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
        source_dir: 'zip'
        destination_dir: ''
