
name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: shallwefootball/s3-upload-action@master
      name: Release to S3
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_ACCESS_SECRET}}
        aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
        source_dir: 'scripts'
        destination_dir: 'scripts'
        
